services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chat-network

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - chat-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/chat
      JWT_SECRET: supersecret
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      - postgres
      - redis
    ports:
      - "3003:3000"
    networks:
      - chat-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    environment:
      - CHOLIDAR_USEPOLLING=true
    networks:
      - chat-network

volumes:
  pgdata:

networks:
  chat-network:
    driver: bridge
